
server:
  port: 8002
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tahauddin
    username: <Your User Name>
    password: <Your Password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  show-sql: true
  sql:
    init:
      mode: always


